apiVersion: v1
kind: Service
metadata:
  name: {{ default "postgresdb" .Values.app.name }}-service
  labels:
    app: {{ default "postgresdb" .Values.app.name }}
spec:
  type: NodePort
  selector:
    app: {{ default "postgresdb" .Values.app.name }}
  ports:
  - port: {{ .Values.app.port }}
    targetPort: 5432
