version: '3.8'
services:
  auth-microservices:
    container_name: auth-microservices
    build:
      context: ./dockerfiles/microservices/auth
      dockerfile: auth.dockerfile
    working_dir: /app
    volumes:
      - ./microservices/auth-microservices:/app
    ports:
      - "3002:3000"
    depends_on:
      - influxdb
      - nats-server
      - mosquitto
      - nats-box

  db-logger-microservices:
    container_name: db-logger-microservices
    build:
      context: ./dockerfiles/microservices/db-logger
      dockerfile: db-logger.dockerfile
    working_dir: /app
    volumes:
      - ./microservices/db-logger-microservices:/app
    ports:
      - "3001:3000"
    depends_on:
      - influxdb
      - nats-server
      - mosquitto
      - nats-box

  influxdb:
    image: influxdb:2.1.0-alpine
    container_name: influxdb
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASS}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG} 
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb

  nats-server:
    container_name: nats-server
    build:
      context: ./dockerfiles
      dockerfile: nats.dockerfile
      args:
        - NATS_VERSION=${NATS_VERSION:-alpine}
    ports:
      - 1883:1883
      - 4222:4222

   # Eclipse Mosquitto MQTT Broker
  mosquitto:
    container_name: mosquitto
    build:
      context: ./dockerfiles
      dockerfile: mqtt.dockerfile
      args:
        - MOSQUITTO_VERSION=${MOSQUITTO_VERSION:-latest}
    environment:
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}
    restart: always
    volumes:
      - ./scripts:/scripts
    ports:
      - 1884:1883

  #NATS Client
  nats-box:
    container_name: nats-box
    image: synadia/nats-box:latest
    stdin_open: true
    tty: true

volumes:
  influxdb_data:

networks:
  default:
    name: nats_mqtt_network
    driver: bridge