version: '3.8'
services:
  web-app:
    container_name: web-app
    build:
      context: ./dockerfiles/application/web-app
      dockerfile: web-app.dockerfile
    working_dir: /app
    volumes:
      - ./application/web-app:/app
    ports:
      - "8080:8080"
      - "3031:3031"
    depends_on:
      - things-service
      - db-logger-service
      - notification-service
  
  web-app-prod:
    container_name: web-app-prod
    image: zulfikar4568/web-app
    ports:
      - "8080:80"
    env_file:
      - application/web-app/.env

  db-logger-service:
    container_name: db-logger-service
    build:
      context: ./dockerfiles/microservices/db-logger
      dockerfile: db-logger.dockerfile
    working_dir: /app
    volumes:
      - ./microservices/db-logger-service:/app
    ports:
      - "3001:3000"
      - "9229:9229"
    env_file:
      - microservices/db-logger-service/.env
    depends_on:
      - influxdb
      - nats-server
      - mosquitto
      - nats-box

  db-logger-service-prod:
    container_name: db-logger-service-prod
    image: zulfikar4568/db-logger-service
    ports:
      - "3001:3000"
    env_file:
      - microservices/db-logger-service/.env
    depends_on:
      - influxdb
      - nats-server
      - mosquitto
      - nats-box

  auth-service:
    container_name: auth-service
    build:
      context: ./dockerfiles/microservices/auth
      dockerfile: auth.dockerfile
    working_dir: /app
    volumes:
      - ./microservices/auth-service:/app
    ports:
      - "3002:3000"
      - "9230:9229"
      - "5555:5555"
    env_file:
      - microservices/auth-service/.env
    depends_on:
      - influxdb
      - nats-server
      - mosquitto
      - nats-box
      - postgres-db
  
  auth-service-prod:
    container_name: auth-service-prod
    image: zulfikar4568/auth-service
    ports:
      - "3002:3000"
    env_file:
      - microservices/auth-service/.env
    depends_on:
      - influxdb
      - nats-server
      - mosquitto
      - nats-box
      - postgres-db

  things-service:
    container_name: things-service
    build:
      context: ./dockerfiles/microservices/things
      dockerfile: things.dockerfile
    working_dir: /app
    volumes:
      - ./microservices/things-service:/app
    ports:
      - "3003:3000"
      - "9231:9229"
    env_file:
      - microservices/things-service/.env
    depends_on:
      - influxdb
      - nats-server
      - mosquitto
      - nats-box
      - postgres-db
  
  things-service-prod:
    container_name: things-service-prod
    image: zulfikar4568/things-service
    ports:
      - "3003:3000"
    env_file:
      - microservices/things-service/.env
    depends_on:
      - influxdb
      - nats-server
      - mosquitto
      - nats-box
      - postgres-db
  
  notification-service:
    container_name: notification-service
    build:
      context: ./dockerfiles/microservices/notification
      dockerfile: notification.dockerfile
    working_dir: /app
    volumes:
      - ./microservices/notification-service:/app
    ports:
      - "3004:3000"
      - "9232:9229"
    env_file:
      - ./microservices/notification-service/.env
    depends_on:
      - influxdb
      - nats-server
      - mosquitto
      - nats-box
      - postgres-db
  notification-service-prod:
    container_name: notification-service-prod
    image: zulfikar4568/notification-service
    ports:
      - "3004:3000"
    env_file:
      - ./microservices/notification-service/.env
    depends_on:
      - influxdb
      - nats-server
      - mosquitto
      - nats-box
      - postgres-db
      
  postgres-db:
    container_name: postgres-db
    image: postgres:14.3-alpine
    restart: always
    volumes:
      - ./dockerfiles/database/postgres:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_MULTIPLE_DATABASES}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  pg-admin4:
    container_name: pg-admin4
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}

  kong-database:
    container_name: kong-database
    image: postgres:9.6
    restart: always
    volumes:
      - kong-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${KONG_POSTGRES_DB}
      - POSTGRES_USER=${KONG_POSTGRES_USER}
      - POSTGRES_PASSWORD=${KONG_POSTGRES_PASSWORD}

  kong-migrate:
    container_name: kong-migrate
    image: kong:2.3.3
    restart: on-failure
    command: kong migrations bootstrap
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=${KONG_POSTGRES_DB}
      - KONG_PG_USER=${KONG_POSTGRES_USER}
      - KONG_PG_PASSWORD=${KONG_POSTGRES_PASSWORD}
    depends_on:
      - kong-database

  kong:
    container_name: kong
    image: kong:2.3.3
    restart: always
    environment:
      - KONG_LOG_LEVEL=debug
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=${KONG_POSTGRES_DB}
      - KONG_PG_USER=${KONG_POSTGRES_USER}
      - KONG_PG_PASSWORD=${KONG_POSTGRES_PASSWORD}
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_PROXY_LISTEN_SSL=0.0.0.0:8443
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
    depends_on:
      - kong-migrate
      - kong-database

  konga-prepare:
    container_name: konga-prepare
    image: pantsel/konga:0.14.9
    command: "-c prepare -a postgres -u postgresql://${KONG_POSTGRES_USER}:${KONG_POSTGRES_PASSWORD}@kong-database:5432/${KONGA_POSTGRES_DB}"
    restart: on-failure
    links:
      - kong-database
    depends_on:
      - kong-database
  
  konga:
    container_name: konga
    image: pantsel/konga:0.14.9
    restart: on-failure
    environment:
      - DB_ADAPTER=postgres
      - DB_HOST=kong-database
      - DB_USER=${KONG_POSTGRES_USER}
      - DB_PASSWORD=${KONG_POSTGRES_PASSWORD}
      - TOKEN_SECRET=km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
      - DB_DATABASE=${KONGA_POSTGRES_DB}
    depends_on:
      - kong-database
    ports:
      - "1337:1337"

  influxdb:
    image: influxdb:2.1.0-alpine
    container_name: influxdb
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASS}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG} 
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb

  nats-server:
    container_name: nats-server
    build:
      context: ./dockerfiles
      dockerfile: nats.dockerfile
      args:
        - NATS_VERSION=${NATS_VERSION:-alpine}
    ports:
      - 1883:1883
      - 4222:4222
      - 9000:9090

   # Eclipse Mosquitto MQTT Broker
  mosquitto:
    container_name: mosquitto
    build:
      context: ./dockerfiles
      dockerfile: mqtt.dockerfile
      args:
        - MOSQUITTO_VERSION=${MOSQUITTO_VERSION:-latest}
    environment:
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}
    restart: always
    volumes:
      - ./scripts:/scripts
    ports:
      - 1884:1883

  #NATS Client
  nats-box:
    container_name: nats-box
    platform: linux/amd64
    image: natsio/nats-box:latest
    stdin_open: true
    tty: true

  mail-dev:
    container_name: mail-dev
    image: maildev/maildev
    ports:
      - ${EMAIL_SMTP_SERVER_PORT}:${EMAIL_SMTP_SERVER_PORT}
      - ${EMAIL_SMTP_WEB}:${EMAIL_SMTP_WEB}
    command: bin/maildev -w ${EMAIL_SMTP_WEB} -s ${EMAIL_SMTP_SERVER_PORT} --outgoing-host ${EMAIL_OUTGOING_HOST} --outgoing-user ${EMAIL_OUTGOING_ID} --outgoing-pass ${EMAIL_OUTGOING_PASS} --outgoing-port ${EMAIL_OUTGOING_PORT}
    
volumes:
  influxdb_data:
  postgres_data:
  kong-db-data:

networks:
  default:
    name: nats_mqtt_network
    driver: bridge