{{range $i, $value := .Values.microservices | default dict}}
{{if and $value.externalPort $value.port $value.enabled}}
---

apiVersion: v1
kind: Service
metadata:
  name: vechr-microservice-{{$value.name}}
  labels:
    app: vechr-microservice-{{$value.name}}
spec:
  type: ClusterIP
  selector:
    app: vechr-microservice-{{$value.name}}
  ports:
    - port: {{$value.externalPort}}
      targetPort: {{$value.port}}
      protocol: TCP
      name: http

{{end}}
{{end}}