cluster:
  enabled: true
  replicas: 3
  noAdvertise: true

nats:
  image: nats:alpine
  jetstream:
    enabled: true

    memStorage:
      enabled: true
      size: 2Gi

    fileStorage:
      enabled: true
      size: 1Gi
      storageDirectory: /data/

mqtt:
  enabled: true
  port: 1883

websocket:
  enabled: true
  port: 9090

natsbox:
  enabled: true