{{if .Values.ingresses.enabled}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.ingresses.name}}
  namespace:  {{.Values.ingresses.namespace}}
spec:
  ingressClassName:  {{.Values.ingresses.ingressClassName}}
  {{if .Values.ingresses.tls.enabled}}
  tls:
  - hosts: 
      {{if .Values.ingresses.tls.hosts}}
      {{range $i, $host := .Values.ingresses.tls.hosts}}
      - {{$host}}
      {{end}}
      {{end}}
    secretName: {{.Values.ingresses.tls.secretName}}
  {{end}}
  rules:
  {{if .Values.ingresses.rules}}
  {{range $i, $rule := .Values.ingresses.rules}}
  - host: {{$rule.host}}
    http:
      {{ if $rule.services}}
      paths:
        {{range $j, $service := $rule.services}}
        - path: {{$service.path}}
          pathType: Prefix
          backend:
            service:
              name: {{$service.name}}
              port:
                number: {{$service.port}}
        {{end}}
      {{end}}
  {{end}}
  {{end}}
{{end}}