{{if .Values.ingresses.tls.enabled}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.ingresses.tls.secretName}}
type: kubernetes.io/tls
data:
  ca.crt: {{.Values.ingresses.tls.ca}}
  tls.crt: {{.Values.ingresses.tls.cert}}
  tls.key: {{.Values.ingresses.tls.key}}
{{end}}