---
name: Bug Report
description: Create a report to help us improve software
title: "Bug Report"
labels: ["type: bug"]
assignees: "Zulfikar"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your time, to fill this report!
  - type: textarea
    id: current
    attributes:
      label: Current Issue
      description: Tell as what the issue
      placeholder: e.g., When create dashboard some field cannot be created
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: To be expected
      description: Tell as what should be expected instead of issued
      placeholder: e.g., Field device should be fill, instead of null
  - type: textarea
    id: logs
    attributes:
      label: Log Output(if any)
      description: Please Copy and Paste, if you have some logs error
      placeholder: |
        e.g.
        {
          code: 401,
          message: Field cannot be null!
          ....
        }
    validations:
      required: false
  - type: textarea
    id: possible-solution
    attributes:
      label: Possible Solution
      description: Not obligatory, but suggest a fix/reason for the bug
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version that you used?
      options:
        - v1.0.x
        - v1.1.x
        - not applicable
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Is there any reference?

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false