apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}"
  labels:
    app: "{{ .Values.name }}"
spec:
  type: ClusterIP
  selector:
    app: "{{ .Values.name }}"
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.service.port }}
      targetPort: 3000