apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vechr-development
  namespace: argocd
spec:
  project: vechr
  source:
    repoURL: 'https://vechr.github.io/vechr-atlas/helm/charts/'
    targetRevision: 1.0.5
    chart: vechr
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'